# Generated by Django 2.2.7 on 2019-11-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urlshortener', '0002_delete_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=250, verbose_name='Long URL')),
                ('url_id', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
